name: Build and deploy

on: [push]

permissions:
  contents: write

jobs:
  deploy-gh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Projects
